# Generated by Django 5.1.2 on 2024-10-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Country_Orgin', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufactured_By', models.CharField(blank=True, max_length=100, null=True)),
                ('P_Image1', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('P_Image2', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('P_Image3', models.ImageField(blank=True, null=True, upload_to='Product')),
            ],
        ),
    ]
