# Generated by Django 5.1.2 on 2024-10-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Login_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Login_Mobile', models.IntegerField(blank=True, null=True)),
                ('Login_Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Login_Repassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
