# Generated by Django 5.1.2 on 2024-11-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_login_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Total_Price', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Holder', models.CharField(blank=True, max_length=100, null=True)),
                ('P_Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
