# Generated by Django 5.1.2 on 2024-11-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cart_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_db',
            name='Product_Pic',
        ),
    ]
