# Generated by Django 5.1.2 on 2024-11-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cart_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_db',
            name='P_Image',
            field=models.ImageField(blank=True, null=True, upload_to='cart'),
        ),
    ]
