# Generated by Django 5.1.2 on 2024-11-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_cart_db_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_db',
            name='P_Image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
